[project]
name = "ahc-template"
version = "0.1.0"
description = "Reusable scaffold for AtCoder Heuristic Contests"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "ruff>=0.14.1",
]

[tool.ruff.lint]
select = ["E", "F", "I"]
